# Model can be "lseq" or "usleep"
model: "usleep"

training:
 iterations: 28352
 batch_size: 64
 use_gpu: True
 use_pretrained: False
 test: False
 pretrained_path: ".neptune/lseq/BIG-300/checkpoints/latest.ckpt"
 max_epochs: 100
 early_stop_patience: 100000
 lr_patience: 100000
 lr_reduction: 0.5
 subject_percentage: 1.0
 devices: 1
 num_nodes: 1
 datasplit_path: "/home/js/repos/common-sleep-data-pipeline/common_sleep_data_pipeline/shared/splits/usleep_split.json"
 num_workers: 8
 augmentation:
  use: False
  min_frac: 0.001
  max_frac: 0.3
  apply_prob: 0.1
  sigma: 1.0
  mean: 0.0
 
neptune:
 log: True
 api_key: "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI5YzViZjJlYy00NDNhLTRhN2EtOGZmYy00NDEzODBmNTgxYzMifQ=="
 project: "NTLAB/bigsleep"
 
datasets:
 base_path: "/com/ecent/NOBACKUP/HDF5/usleep_data_small"
 train:
  - "abc"
  - "ccshs"
  - "cfs"
  - "chat"
  - "dcsm"
  - "homepap"
  - "mesa"
  - "mros"
  - "shhs"
  - "phys"
  - "sof"
 val:
  - "abc"
  - "ccshs"
  - "cfs"
  - "chat"
  - "dcsm"
  - "homepap"
  - "mesa"
  - "mros"
  - "shhs"
  - "phys"
  - "sof"
 test:
  - "abc"

model_parameters:
  lseq:
    features: 129
    epochs: 200
    sequences: 29
    classes: 5
    lr: 2.0E-03
    seed: 4
    weight_decay: 0.001
    F: 129
    M: 32
    num_channels: 2
    minF: 0
    maxF: 50
    source_samplerate: 128
    samplerate: 100
    K: 10
    B: 20
    lstm_hidden_size: 64
    fc_hidden_size: 512
    classes: 5
    attention_size: 64

  usleep:
    epochs: 35
    lr: 1.0E-06
