# Model can be "usleep" or "lseqsleepnet"
model: "usleep"

hdf5_base_path: "/users/strmjesp/mnt/Big_Sleep_Set/transformed"

hdf5_split_path: "/users/strmjesp/common-sleep-data-pipeline/csdp_pipeline/splits/usleep_split.json"

accelerator: "gpu"

train_sets:
  - "abc"
  - "ccshs"
  - "cfs"
  - "chat"
  - "dcsm"
  - "homepap"
  - "sedf_sc"
  - "sedf_st"
  - "mesa"
  - "mros"
  - "shhs"
  - "phys"
  - "sof"
val_sets:
  - "abc"
  - "ccshs"
  - "cfs"
  - "chat"
  - "dcsm"
  - "homepap"
  - "sedf_sc"
  - "sedf_st"
  - "mesa"
  - "mros"
  - "shhs"
  - "phys"
  - "sof"
test_sets:
  - "abc"
  - "ccshs"
  - "cfs"
  - "chat"
  - "dcsm"
  - "homepap"
  - "sedf_sc"
  - "sedf_st"
  - "mesa"
  - "mros"
  - "shhs"
  - "phys"
  - "sof"

test_after_train: True
test_only: False

gradient_steps: 443
batch_size: 64
num_workers: 8
lr: 0.0001
max_epochs: 300
early_stop_patience: 1000

usleep_parameters:
  initial_filters: 5
  complexity_factor: 1.0
  progression_factor: 2

lseq_parameters:
  coming_soon: 0

pretrained: False
pretrained_path: "/users/strmjesp/mnt/.neptune/usleep/BIG-633/checkpoints/epoch=269-step=119610.ckpt"

train_percentage: 0.75

neptune:
  logging: True
  existing_run_id: null
  logging_folder: "/users/strmjesp/mnt"
  api_key: "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI5YzViZjJlYy00NDNhLTRhN2EtOGZmYy00NDEzODBmNTgxYzMifQ=="
  project: "NTLAB/bigsleep"
  name: "usleep"
