# Model can be "usleep" or "lseqsleepnet"
model: "usleep"

hdf5_base_path: "C:/Users/au588953/hdf5"

hdf5_split_path: "C:/Users/au588953/Git Repos/CSDP/csdp_pipeline/splits/usleep_split.json"
accelerator: "cpu"

train_sets:
  - "abc"
  - "ccshs"
  - "cfs"
  - "chat"
  - "dcsm"
  - "homepap"
  - "mesa"
  - "mros"
  - "shhs"
  - "phys"
  - "sof"
val_sets:
  - "abc"
  - "ccshs"
  - "cfs"
  - "chat"
  - "dcsm"
  - "homepap"
  - "mesa"
  - "mros"
  - "shhs"
  - "phys"
  - "sof"
test_sets:
  - "ccshs"

gradient_steps: 10
batch_size: 64
num_workers: 1
lr: 0.00001
max_epochs: 1
early_stop_patience: 50

usleep_parameters:
  initial_filters: 5
  complexity_factor: 1.67
  progression_factor: 2

lseq_parameters:
  coming_soon: 0

pretrained: True
pretrained_path: "C:/Users/au588953/Git Repos/CSDP/checkpoints/best_usleep.ckpt"

neptune:
  logging: False
  existing_run_id: null
  logging_folder: null
  api_key: "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI5YzViZjJlYy00NDNhLTRhN2EtOGZmYy00NDEzODBmNTgxYzMifQ=="
  project: "NTLAB/bigsleep"
  name: "usleep"
