environment: "LOCAL"

train_sets:
  - cfs
val_sets:
  - cfs
test_sets:
  - cfs

pretrained: False
pretrained_path: ""

gradient_steps: 5
batch_size: 64
num_workers: 8

lr: 0.000001
max_epochs: 100
early_stop_patience: 50

neptune:
  logging: False
  api_key: "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI5YzViZjJlYy00NDNhLTRhN2EtOGZmYy00NDEzODBmNTgxYzMifQ=="
  project: "NTLAB/bigsleep"
  name: "usleep"